apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: webreplica
  name: webreplica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webreplica
  template:
    metadata:
      labels:
        app: webreplica
    spec:
      containers:
      - image: nginx:latest
        name: nginx